<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Events Report - Rwanda EventHub</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        h1 { font-size: 24px; color: #4F46E5; margin-bottom: 5px; }
        h2 { font-size: 18px; color: #666; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #4F46E5; color: white; padding: 10px; text-align: left; font-size: 11px; text-transform: uppercase; }
        td { padding: 8px 10px; border-bottom: 1px solid #eee; font-size: 11px; }
        tr:nth-child(even) { background: #f9f9f9; }
        .footer { margin-top: 30px; text-align: center; color: #999; font-size: 10px; }
    </style>
</head>
<body>
    <h1>Rwanda EventHub</h1>
    <h2>Events Report - {{ date('F d, Y') }}</h2>

    <table>
        <thead>
            <tr>
                <th>Title</th>
                <th>Category</th>
                <th>Organizer</th>
                <th>Date</th>
                <th>Location</th>
                <th>Status</th>
                <th>Invitations</th>
            </tr>
        </thead>
        <tbody>
            @foreach($events as $event)
                <tr>
                    <td>{{ $event->title }}</td>
                    <td>{{ $event->category_name }}</td>
                    <td>{{ $event->organizer->full_name ?: $event->organizer->name }}</td>
                    <td>{{ $event->event_date->format('M d, Y') }}</td>
                    <td>{{ $event->location }}, {{ $event->province_name }}</td>
                    <td>{{ $event->status_name }}</td>
                    <td>{{ $event->invitations_count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Rwanda EventHub on {{ date('Y-m-d H:i:s') }}</p>
        <p>Total Events: {{ $events->count() }}</p>
    </div>
</body>
</html>
