<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Users Report - Rwanda EventHub</title>
    <style>
        body { font-family: sans-serif; font-size: 12px; color: #333; }
        h1 { font-size: 24px; color: #4F46E5; margin-bottom: 5px; }
        h2 { font-size: 18px; color: #666; margin-bottom: 20px; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background: #4F46E5; color: white; padding: 10px; text-align: left; font-size: 11px; text-transform: uppercase; }
        td { padding: 8px 10px; border-bottom: 1px solid #eee; font-size: 11px; }
        tr:nth-child(even) { background: #f9f9f9; }
        .footer { margin-top: 30px; text-align: center; color: #999; font-size: 10px; }
        .badge { padding: 3px 8px; border-radius: 10px; font-size: 10px; }
        .active { background: #d1fae5; color: #065f46; }
        .suspended { background: #fce7f3; color: #9f1239; }
    </style>
</head>
<body>
    <h1>Rwanda EventHub</h1>
    <h2>Users Report - {{ date('F d, Y') }}</h2>

    <table>
        <thead>
            <tr>
                <th>Name</th>
                <th>Email</th>
                <th>Role</th>
                <th>Status</th>
                <th>Joined</th>
                <th>Invitations</th>
            </tr>
        </thead>
        <tbody>
            @foreach($users as $user)
                <tr>
                    <td>{{ $user->full_name ?: $user->name }}</td>
                    <td>{{ $user->email }}</td>
                    <td>{{ ucfirst(str_replace('_', ' ', $user->role)) }}</td>
                    <td>{{ ucfirst($user->status) }}</td>
                    <td>{{ $user->created_at->format('M d, Y') }}</td>
                    <td>{{ $user->invitations_count }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        <p>Generated by Rwanda EventHub on {{ date('Y-m-d H:i:s') }}</p>
        <p>Total Users: {{ $users->count() }}</p>
    </div>
</body>
</html>
